# -*- coding: utf-8 -*-
"""Autograd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szT2CnaTrvz-kt9bSnd7X97kkk2Suie5
"""

import math

class Tensor:
    def __init__(self, data, _children=(), _op=''):
        self.data = float(data)
        self.grad = 0.0
        self._prev = set(_children)
        self._op = _op
        self._backward = lambda: None

    def __repr__(self):
        return f"Tensor(data={self.data:.4f}, grad={self.grad:.4f})"

    # ---------------- ops ----------------
    def __add__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data + other.data, (self, other), '+')

        def _backward():
            self.grad += out.grad
            other.grad += out.grad

        out._backward = _backward
        return out

    def __mul__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data * other.data, (self, other), '*')

        def _backward():
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad

        out._backward = _backward
        return out

    def __neg__(self):
        return self * -1

    def __sub__(self, other):
        return self + (-other)

    # ---------------- activation ----------------
    def sigmoid(self):
        s = 1 / (1 + math.exp(-self.data))
        out = Tensor(s, (self,), 'sigmoid')

        def _backward():
            self.grad += s * (1 - s) * out.grad

        out._backward = _backward
        return out

    # ---------------- backprop ----------------
    def backward(self):
        topo = []
        visited = set()

        def build(v):
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build(child)
                topo.append(v)

        build(self)

        self.grad = 1.0
        for node in reversed(topo):
            node._backward()

def bce(pred, target):
    eps = 1e-7
    p = min(max(pred.data, eps), 1 - eps)

    loss = -(target.data * math.log(p) +
             (1 - target.data) * math.log(1 - p))

    out = Tensor(loss, (pred,), 'bce')

    def _backward():
        pred.grad += ((-target.data / p) +
                      (1 - target.data) / (1 - p)) * out.grad

    out._backward = _backward
    return out

X = [
    (0, 0),
    (0, 1),
    (1, 0),
    (1, 1)
]

y = [0, 0, 0, 1]

import random

w1 = Tensor(random.uniform(-1, 1))
w2 = Tensor(random.uniform(-1, 1))
b  = Tensor(0.0)

lr = 0.1

for epoch in range(200):
    total_loss = 0

    for (x1, x2), target in zip(X, y):

        # forward
        x1 = Tensor(x1)
        x2 = Tensor(x2)

        z = x1 * w1 + x2 * w2 + b
        pred = z.sigmoid()

        loss = bce(pred, Tensor(target))
        total_loss += loss.data

        # backward
        loss.backward()

        # update weights
        w1.data -= lr * w1.grad
        w2.data -= lr * w2.grad
        b.data  -= lr * b.grad

        # zero grads
        w1.grad = 0
        w2.grad = 0
        b.grad = 0

    if epoch % 20 == 0:
        print(f"epoch {epoch}, loss {total_loss:.4f}")



